# Generated by Django 5.0.3 on 2024-03-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_alter_artist_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
