# Generated by Django 5.0.3 on 2024-03-15 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_artist_id'),
        ('user', '0003_alter_user_managers_user_artist_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='artist_following',
            field=models.ManyToManyField(null=True, related_name='users', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
