# Generated by Django 5.0.3 on 2024-03-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_artist_following_alter_user_followings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(default="wsqh3178hkjq", max_length=128),
            preserve_default=False,
        ),
    ]
